/*
 * WARNING: Do not edit this file directly on the wiki!
 * This file is automatically generated from the TypeScript source.
 * Make changes in the GitHub repository instead:
 * https://github.com/mplewis/dominion-strategy-wiki
 *
 * Your changes here will be overwritten by the automated deployment process.
 */

/* Any JavaScript here will be loaded for all users on every page load. */

import { initCommon } from "./core/initialization";

(() => {
  try {
    initCommon();
  } catch (_error) {
    console.info("initCommon called too early!");
    // jQuery fallback for environments that need it
    if (typeof $ !== "undefined") {
      $(document).ready(initCommon);
    } else {
      document.addEventListener("DOMContentLoaded", initCommon);
    }
  }
})();
