name: Update Featured Article

on:
  schedule:
    # Run every Sunday at 08:00 Mountain Time (15:00 UTC)
    - cron: "0 15 * * 0"
  workflow_dispatch: # Allow manual triggering

jobs:
  update-featured-article:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "10.14.0"

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Update featured article
        run: pnpm update-featured-article --confirm-edit
        env:
          MEDIAWIKI_USERNAME: ${{ vars.MEDIAWIKI_USERNAME }}
          MEDIAWIKI_PASSWORD: ${{ secrets.MEDIAWIKI_PASSWORD }}
